### ISSUE TITLE
feature request: create docker container

### ISSUE THREAD

**Issue by hartmark** [curzon01/mqtt2sql#32]
I'd love to have this as a self contained docker container to keep the program more isolated so it's easier to update. Now with latest update I needed to fiddle and install some python libraries.

**Comment by curzon01** [comment]
I'm not sure which is easier, installing a lib for Python or configuring a docker to an external database and MQTT server. It is not my intention to additionally embed both services in this solution. A docker for a small Python tool like this feels like shooting sparrows with cannons.

What I can rather imagine is a PyPi package

**Comment by curzon01** [comment]
> is a PyPi package something you can install like a aur-package in arch Linux?

see [pypi.org](https://pypi.org/) - you do `pip install <package>` to install the package and dependencies.

But I still don't see the milestone: This tool system still needs a Python environment and for external resources an MQTT server and possibly a MySQL server. That is the meaning behind it. Since I don't plan to integrate the last two services into this tool, the only thing left to do is to install a Python environment and the dependencies. But all this is already done by the simple two-line solution from [Installation - Python prerequisites](https://github.com/curzon01/mqtt2sql?tab=readme-ov-file#python-prerequisites)

**Comment by curzon01** [comment]
> Yeah, it's probably a bit overkill

that's the point

**Comment by curzon01** [comment]
Any PR is welcome, otherwise I will close the request
